# Generated by Django 5.0.4 on 2024-05-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_products_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_video',
            field=models.FileField(blank=True, null=True, upload_to='products/video'),
        ),
    ]
