# Generated by Django 5.0.4 on 2024-05-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_products_product_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_video',
        ),
    ]
