# Generated by Django 5.0.4 on 2024-05-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_products_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Discounted Price'),
        ),
    ]
