# Generated by Django 5.0.4 on 2024-05-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_products_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialHandlers',
        ),
    ]
