# Generated by Django 5.0.4 on 2024-05-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='buyer_zip',
            new_name='buyer_zip_code',
        ),
    ]
