# Generated by Django 5.0.4 on 2024-05-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_rename_buyer_zip_purchase_buyer_zip_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
