# Generated by Django 5.0.4 on 2024-05-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_delivery_charge',
            field=models.IntegerField(default=0),
        ),
    ]
