# Generated by Django 5.0.4 on 2024-05-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_products_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_tax_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
