# Generated by Django 5.0.4 on 2024-06-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
