# Generated by Django 5.0.4 on 2024-05-13 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0012_products_product_discounted_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_number', models.CharField(max_length=13)),
                ('user_profile_picture', models.ImageField(blank=True, null=True, upload_to='users/dp')),
                ('user_purchases', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_followers_no', models.IntegerField()),
                ('user_following_no', models.IntegerField()),
                ('user_notifications_no', models.IntegerField()),
                ('user_followers', models.CharField(blank=True, max_length=100, null=True)),
                ('user_following', models.CharField(blank=True, max_length=100, null=True)),
                ('user_messages_received', models.TextField(blank=True, null=True, verbose_name='Messages Received')),
                ('user_attachedfile_receive', models.FileField(blank=True, null=True, upload_to='users/rec/att')),
                ('user_attachedfile_send', models.FileField(blank=True, null=True, upload_to='users/send/att')),
                ('user_messages_send', models.TextField(blank=True, null=True, verbose_name='Messages Sent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_cart_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_list', to='product.products')),
                ('user_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_interest', to='product.products')),
                ('user_recent_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_recent_purchase', to='product.products')),
                ('user_recent_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_recent_sales', to='product.products')),
                ('user_search_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_search_history', to='product.products')),
                ('user_wish_list', models.ManyToManyField(blank=True, related_name='wishlisted_users', to='product.products')),
            ],
        ),
    ]
