# Generated by Django 5.0.4 on 2024-05-15 07:54

import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(default=django.contrib.auth.base_user.AbstractBaseUser.get_username, max_length=100),
        ),
    ]
