# Generated by Django 5.0.4 on 2024-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user_email',
            field=models.CharField(default='email', max_length=320),
        ),
        migrations.AddField(
            model_name='member',
            name='user_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
