# Generated by Django 5.0.4 on 2024-05-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_user_email_member_user_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user_about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
