# Generated by Django 5.0.4 on 2024-05-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_member_user_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_notifications_no',
        ),
        migrations.AlterField(
            model_name='member',
            name='user_followers_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_following_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_sales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
