# Generated by Django 5.0.4 on 2024-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_member_user_remove_member_user_wish_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_wish_list',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
