# Generated by Django 5.0.4 on 2024-05-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_alter_member_user_wish_list'),
        ('product', '0015_alter_products_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_wish_list',
        ),
        migrations.AddField(
            model_name='member',
            name='user_wish_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlisted_users', to='product.products'),
        ),
    ]
