# Generated by Django 5.0.4 on 2024-05-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_alter_member_user_wish_list'),
        ('product', '0015_alter_products_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_cart_list',
        ),
        migrations.AddField(
            model_name='member',
            name='user_cart_list',
            field=models.ManyToManyField(blank=True, related_name='user_cart_list', to='product.products'),
        ),
    ]
