# Generated by Django 5.0.4 on 2024-05-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
