# Generated by Django 5.0.4 on 2024-05-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
