# Generated by Django 5.0.4 on 2024-05-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_invoice_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
