# Generated by Django 5.0.4 on 2024-05-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_delete_invoice'),
        ('product', '0024_purchase_sellor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_recent_purchase',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_recent_sales',
        ),
        migrations.AddField(
            model_name='member',
            name='user_recent_purchase',
            field=models.ManyToManyField(related_name='user_recent_purchase', to='product.products'),
        ),
        migrations.AddField(
            model_name='member',
            name='user_recent_sales',
            field=models.ManyToManyField(related_name='user_recent_sales', to='product.products'),
        ),
    ]
