# Generated by Django 5.0.4 on 2024-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_remove_member_user_recent_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_purchases',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
