# Generated by Django 5.0.4 on 2024-05-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0022_alter_member_user_cart_list_and_more'),
        ('product', '0025_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_email',
            field=models.CharField(max_length=320),
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_interest',
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='user_interest',
            field=models.ManyToManyField(to='product.products'),
        ),
    ]
