# Generated by Django 5.0.4 on 2024-05-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0024_alter_member_user_cart_list_and_more'),
        ('product', '0025_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_order', models.ManyToManyField(to='product.purchase')),
            ],
        ),
    ]
