# Generated by Django 5.0.4 on 2024-06-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0031_messages_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='receiver',
        ),
    ]
