# Generated by Django 5.0.4 on 2024-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0033_messages_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_messages_received',
        ),
        migrations.AddField(
            model_name='member',
            name='user_messages_received',
            field=models.ManyToManyField(to='member.messages'),
        ),
    ]
