# Generated by Django 5.0.4 on 2024-06-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0034_remove_member_user_messages_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_messages_send',
        ),
        migrations.AddField(
            model_name='member',
            name='user_messages_send',
            field=models.ManyToManyField(related_name='sent', to='member.messages'),
        ),
    ]
